### PR TITLE
Somatic fix

### PR DESCRIPTION
**Pull request by chrisamiller**
The new containers added here either don't have needed tools (sanitize) or segfault (merge). Rolling these back to older versions.

### CODE REVIEW

**Comment by gschang** [comment]
(+1) This needs fixing ASAP.

Thank you for this work, @chrisamiller. As you pointed, I had the same problem in ../tools/vcf_sanitize.cwl, but I didn't dig it up yesterday. I just know that this problem is also owing to the new docker container. As updated, I am testing somatic_exome workflow with example data. I will keep you posted if I find another issues.

**Review by tmooney — DISMISSED** [review]
+1, though I might prefer if you cherry-picked the commit that matters onto a clean branch 😄

**Comment by tmooney** [comment]
What issues did you run into on the sanitize step?  It looks like tabix and bgzip are both available in the newer image, albeit at different paths.

**Comment by chrisamiller** [comment]
Sorry - my notes got mixed up.  tabix and bgzip do indeed exist in the quay container, but perl does not.

**Comment by chrisamiller** [comment]
Please hold off on this review - I'm doing some additional testing

**Comment by chrisamiller** [comment]
I have screwed up this branch by merging in changes from my other PR - starting over

**Pull request closed without merging**
