### PR TITLE
fixed bug regarding missing indexed bam in bigwig

### PR DESCRIPTION
**Pull request by zlskidmore**
I think there is a small bug in the new rnaseq_star_fusion workflow, the bigwig step is looking for an indexed bam file but no indexed file is getting passed. this results in cwl errors such as this:

{code}
Could not localize /storage1/fs1/obigriffith/Active/gmsroot/model_data/35693d91d68a42d292998a5dd3789c4a/build1aeba2dfb53e4ef592d91c13a231a78a/tmp/cromwell-executions/rnaseq_star_fusion.cwl/24d995d7-a045-4d96-9217-399c3e11ec86/call-mark_dup/execution/MarkedSorted.bai -> /storage1/fs1/obigriffi
th/Active/gmsroot/model_data/35693d91d68a42d292998a5dd3789c4a/build1aeba2dfb53e4ef592d91c13a231a78a/tmp/cromwell-executions/rnaseq_star_fusion.cwl/24d995d7-a045-4d96-9217-399c3e11ec86/call-cgpbigwig_bamcoverage/inputs/-1277726306/MarkedSorted.bai:
        /storage1/fs1/obigriffith/Active/gmsroot/model_data/35693d91d68a42d292998a5dd3789c4a/build1aeba2dfb53e4ef592d91c13a231a78a/tmp/cromwell-executions/rnaseq_star_fusion.cwl/24d995d7-a045-4d96-9217-399c3e11ec86/call-mark_dup/execution/MarkedSorted.bai doesn't exist
        File not found /storage1/fs1/obigriffith/Active/gmsroot/model_data/35693d91d68a42d292998a5dd3789c4a/build1aeba2dfb53e4ef592d91c13a231a78a/tmp/cromwell-executions/rnaseq_star_fusion.cwl/24d995d7-a045-4d96-9217-399c3e11ec86/call-cgpbigwig_bamcoverage/inputs/-1277726306/MarkedSorted.bai
-> /storage1/fs1/obigriffith/Active/gmsroot/model_data/35693d91d68a42d292998a5dd3789c4a/build1aeba2dfb53e4ef592d91c13a231a78a/tmp/cromwell-executions/rnaseq_star_fusion.cwl/24d995d7-a045-4d96-9217-399c3e11ec86/call-mark_dup/execution/MarkedSorted.bai
        File not found /storage1/fs1/obigriffith/Active/gmsroot/model_data/35693d91d68a42d292998a5dd3789c4a/build1aeba2dfb53e4ef592d91c13a231a78a/tmp/cromwell-executions/rnaseq_star_fusion.cwl/24d995d7-a045-4d96-9217-399c3e11ec86/call-mark_dup/execution/MarkedSorted.bai
        at common.validation.Validation$ValidationTry$.toTry$extension1(Validation.scala:89)
        at common.validation.Validation$ValidationTry$.toTry$extension0(Validation.scala:85)
        at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand(StandardAsyncExecutionActor.scala:612)
        ... 32 common frames omitted
[2021-01-14 23:42:21,53] [error] DispatchedConfigAsyncJobExecutionActor [24d995d7cgpbigwig_bamcoverage:NA:1]: Error attempting to Execute
java.lang.Exception: Failed command instantiation
{code}

### CODE REVIEW

**Comment by zlskidmore** [comment]
@tmooney pointed out that stringtie isn't using an indexed bam as well, doesn't seem to be a big deal as rnaseq.cwl doesn't pass an indexed bam to stringtie either and it works fine.

But I wonder if it would run faster if we did pass an indexed bam there, @chrisamiller do you have any ideas on that. I don't run stringtie enough to know what it's doing behind the scenes

**Review by chrisamiller — COMMENTED** [review]
Should stringtie also be using that indexed bam?  

Edit: Never mind! Now I see that it was mentioned upthread. If stringtie runs, I don't think it matters, but I'd go ahead and make the change anyway. It might be doing indexing behind the scenes when it detects a bam without it or something, and that would potentially save time.

**Comment by zlskidmore** [comment]
if it does, we'll need to change tools/stringtie.cwl to accept a secondary file and rnaseq.cwl to use an indexed bam or it will break

**Review by chrisamiller — APPROVED** [review]
seems fine to me!  +1 on the assumption that you've gotten the test data, at least, through a run.

**Review by tmooney — COMMENTED** [review]
Looks like `rnaseq_star_fusion_with_xenosplit.cwl` needs the same fixes as `rnaseq_star_fusion.cwl`.

**Review by chrisamiller — DISMISSED** [review]
+1

**Review by tmooney — APPROVED** [review]
+1 🧯

**Pull request merged**
