### PR TITLE
Bump cnvkit version to support crams

### PR DESCRIPTION
**Pull request by johnegarza**

### CODE REVIEW

**Review by chrisamiller — DISMISSED** [review]
+1

**Review by tmooney — APPROVED** [review]
+1, I'm trusting there are no breaking changes in the new version 😄

**Comment by chrisamiller** [comment]
This version doesn't have python installed at the path specified in the cnvkit CWL (or maybe at all?):
```
# docker.io/etal/cnvkit:0.9.5
$ which python
/usr/bin/python

# docker.io/etal/cnvkit:0.9.8
$ which python
```

**Comment by chrisamiller** [comment]
I can execute the .py directly, but end up with a page full of warnings (though it appears to output help at least...)

```
$ /usr/local/bin/cnvkit.py -h
/usr/local/lib/python2.7/dist-packages/pandas/_libs/__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 9
6, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
/usr/local/lib/python2.7/dist-packages/pandas/__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, go
t 88
```

**Review by chrisamiller — APPROVED** [review]
looks good +1

**Pull request merged**
