### PR TITLE
Updated version of samtools to 1.11

### PR DESCRIPTION
**Pull request by smk5g5**
updated samtools version to 1.11 (uses quay.io image)

### CODE REVIEW

**Comment by chrisamiller** [comment]
I assume that the quay.io container contains bgzip, which is needed by a couple of these steps?  Nothing here that you're altering seems to use tabix, which is the other thing in the container that's being replaced.

**Comment by smk5g5** [comment]
> I assume that the quay.io container contains bgzip, which is needed by a couple of these steps? Nothing here that you're altering seems to use tabix, which is the other thing in the container that's being replaced.

Yes it does contain bgzip I have changed the path to /usr/local/bin/bgzip in the bgzip cwl. I think there are a couple of shell scripts that I may need to change as well that I haven't touched!

**Review by chrisamiller — DISMISSED** [review]
+1

**Review by tmooney — CHANGES_REQUESTED** [review]
As you noted, some of the shell scripts need updating before this can be used.  Since this got an approval, marking request changes to avoid accidental merges :smile:

**Comment by chrisamiller** [comment]
ugh - I thought I checked them all, but `definitions/tools/vcf_sanitize.cwl` needs an update, since it requires tabix. Most of the others are fine, I think...

**Comment by tmooney** [comment]
Noting that `index_vcf.cwl` needs its tabix path updated as well.

**Review by tmooney — APPROVED** [review]
+1 🗝️

**Pull request merged**
