### PR TITLE
Remove bigwig generation from WGS QC process.

### PR DESCRIPTION
**Pull request by tmooney**
The tool is still left in place for now, in case anyone wants to use it for something else.

### CODE REVIEW

**Comment by chrisamiller** [comment]
Why did this remove the tool from the chipseq cwl? (we were using that!) 

If it's a needed change, that's cool, but if not, we'd appreciate reverting it (and will switch to mosdepth or whatever when it becomes available)

**Comment by tmooney** [comment]
It got removed only because it was taken out of `qc_wgs.cwl` and so was removed from anything using that.  The tool is still around, so it could be added separately to chipseq if that'd be helpful.

I suppose this is the downside of reusing components!

**Comment by chrisamiller** [comment]
ah, i see now.  Yeah, we'll add it in as a separate step. Thanks for clarifying!

**Comment by jasonwalker80** [comment]
Keep in mind the reason it was removed. It randomly failed on ~5% of samples. If that's ok, as Tom mentioned, feel free to add it back to chipseq.

**Pull request merged**
