### PR TITLE
Added CNVkit to somatic exome nonhuman and cnvkit_target_average_size to somatic exome

### PR DESCRIPTION
**Pull request by bryanfisk**

### CODE REVIEW

**Review by chrisamiller — APPROVED** [review]
+1 - I don't see any issues here. 

One question - is there a small test data that you used for testing here?  We'd like to get the example data directory to have more comprehensive coverage (if not, we can cross that bridge later).

**Comment by tmooney** [comment]
Are the changes to `detect_variants_wgs.cwl` meant to be included in this PR?  They don't really match up with the included description at all.

**Comment by bryanfisk** [comment]
Well the pipeline would fail until I made those changes but, no, they don't really have much else to do with the CNVkit part.

**Comment by tmooney** [comment]
Yeah, the changes seem like they make sense!  I just didn't see a connection to CNVkit. Ideally if they're not directly related they'd have their own commit or PR (or if nothing else get mentioned in the text of the PR).

**Pull request merged**
